name: Consumer build

on:
  pull_request:
    paths:
      - "consumer/**"
  push:
    branches:
      - master
    paths:
      - "consumer/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Build consumer 🚧"
        run: cd consumer && nix-shell --run "sbt compile"
