name: Producer build

on:
  pull_request:
    paths:
      - "producer/**"
  push:
    branches:
      - master
    paths:
      - "producer/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.1.0

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: hpulsar
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Build producer 🚧"
        run: cd producer && nix-shell --run "cabal new-build"
